"""update meals tabels

Revision ID: 8bfe2551c9f6
Revises: a82530318c17
Create Date: 2024-04-26 19:48:24.194994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfe2551c9f6'
down_revision = 'a82530318c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrision_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prediction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'nutrision', ['nutrision_id'], ['nutrisionId'])
        batch_op.create_foreign_key(None, 'prediction', ['prediction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prediction_id')
        batch_op.drop_column('nutrision_id')

    # ### end Alembic commands ###
