"""Create Nutrision table

Revision ID: e0ab87bbeae5
Revises: 35d5577caf08
Create Date: 2024-03-31 11:48:26.915518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ab87bbeae5'
down_revision = '35d5577caf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrision',
    sa.Column('nutrisionId', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('minerals', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nutrisionId')
    )
    op.create_table('meals',
    sa.Column('mealId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meals_name', sa.String(length=255), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('minerals', sa.Float(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('mealId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals')
    op.drop_table('nutrision')
    # ### end Alembic commands ###
